### ISSUE TITLE
Update Hexerei Datapack to 1.20.1

### ISSUE THREAD

**Issue by brisingraerowing** [TelepathicGrunt/RepurposedStructuresCompatDatapacks#3]
Hexerei is now on 1.20.1, so could the compat datapack be updated / marked compatible?

**Comment by TelepathicGrunt** [comment]
When hexerei v0.4.2 update is out, then put on the newly released updated datapacks. Should be good as verified their new jar will fix issue

**Comment by brisingraerowing** [comment]
👍
